baseURL = "https://bigsmooth68.github.io/"
name = "bigsmooth68.github.io"
author = "Olivier Spiesser"
theme = "paper"
paginate = 7
languageCode = "en"
DefaultContentLanguage = "en"

[params]
  github = 'bigsmooth68'
  linkedin = 'olivierspiesser'
  name = 'Olivier Spiesser'
  bio = 'My blogs posted on dbi services blogs site'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
